# Generated by Django 5.1.6 on 2025-03-04 19:29

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Song',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('genre', models.CharField(max_length=100)),
                ('artist', models.CharField(max_length=100)),
                ('date', models.DateField(verbose_name='Date Published')),
                ('length', models.IntegerField(verbose_name='Length of Song')),
            ],
        ),
    ]
