# Generated by Django 5.1.6 on 2025-03-06 20:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0002_remove_song_artist_artist'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='artist',
            name='album',
        ),
    ]
